// Generate committed static pages from the case/team data. No npm dependencies.
import { readFile, writeFile, mkdir, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = async name => JSON.parse(await readFile(path.join(root, 'data', name), 'utf8'));
const [cases, teams] = await Promise.all([read('cases.json'), read('teams.json')]);
const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const teamById = new Map(teams.map(team => [team.id, team]));
const ids = new Set();
const caseById = new Map(cases.map(record => [record.id, record]));
const dateLabel = record => new Intl.DateTimeFormat('en-US', {
  dateStyle: 'long', timeStyle: 'short', timeZone: record.timeZone
}).format(new Date(record.dateOpened)) + ` (${record.timeZone})`;

function page(title, description, prefix, body) {
  return `<!doctype html>
<!-- Generated by scripts/generate-cases.mjs. Edit data/cases.json, not this file. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#fff5f8">
  <title>${escape(title)} — PNN</title>
  <meta name="description" content="${escape(description)}">
  <link rel="icon" href="${prefix}assets/images/favicon.png" type="image/png">
  <link rel="stylesheet" href="${prefix}assets/css/styles.css">
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <div class="site-shell">
    <header class="masthead">
      <a class="wordmark" href="${prefix}index.html" aria-label="PNN home"><img src="${prefix}assets/images/pnn.svg" width="300" height="110" alt="PNN"></a>
      <span class="masthead-label">Wanted everywhere, caught nowhere.</span>
      <nav class="site-nav" aria-label="Main navigation"><a href="${prefix}cases/index.html">Case files</a><a href="${prefix}tips/index.html">Tip line</a><a href="${prefix}newsletter/index.html">Newsletter</a></nav>
    </header>
    <main id="main" class="case-main">${body}
      <section class="case-teaser tip-callout" aria-labelledby="case-tip-heading"><div><p class="operation-label">PNN Tip Line · Inspector Clueso's office</p><h2 id="case-tip-heading">Clueso has a theory. Have any facts?</h2><p>Help build the fictional case against the Prowling Purrpetrators. Send game reports, approved photos, or corrections to Inspector Clueso's office. All teams' mischief is welcome.</p><p class="hotline-inline">Or call <a href="tel:+18017977265" aria-label="Call the PNN hotline at 801-797-7265">+1 (801) 79-PRANK</a>.</p></div><a class="home-link" href="${prefix}tips/index.html">File a field report →</a></section>
    </main>
    <footer><p>PNN · Purrpetrator News Network<span>Fictional investigations for the Broomstick Challenge neighborhood game.</span></p><a href="${prefix}index.html">Back to headquarters</a><a class="footer-hotline" href="tel:+18017977265" aria-label="Call the PNN hotline at 801-797-7265">PNN Hotline: +1 (801) 79-PRANK</a></footer>
  </div>
</body>
</html>
`;
}

// Validate all records before writing any pages.
for (const record of cases) {
  if (!/^\d{3}$/.test(record.id) || ids.has(record.id)) throw new Error('Case IDs must be unique three-digit strings.');
  ids.add(record.id);
  if (record.caseNumber !== `PNN-${record.id}` || !teamById.has(record.suspectTeamId)) throw new Error(`Invalid case/team reference: ${record.id}`);
  const team = teamById.get(record.suspectTeamId);
  if (!/^assets\/[\w/.-]+\.(jpe?g|png|webp|svg)$/.test(team.logo) || team.logo.split('/').includes('..')) throw new Error(`Invalid team logo: ${record.id}`);
  await access(path.join(root, team.logo));
  if (typeof record.published !== 'boolean') throw new Error(`Missing publication flag: ${record.id}`);
  for (const field of ['dateOpened', 'timeZone', 'status', 'incidentTitle', 'summary', 'incidentDescription', 'suspectedMotive', 'investigatorNote', 'threatLevel', 'disposition']) {
    if (typeof record[field] !== 'string' || !record[field].trim()) throw new Error(`Missing ${field}: ${record.id}`);
  }
  dateLabel(record);
  if (record.relatedCaseIds !== undefined && (!Array.isArray(record.relatedCaseIds) ||
      new Set(record.relatedCaseIds).size !== record.relatedCaseIds.length ||
      record.relatedCaseIds.some(id => typeof id !== 'string' || id === record.id || !caseById.has(id)))) throw new Error(`Invalid related cases: ${record.id}`);
  if (record.organizerNotice) {
    const notice = record.organizerNotice;
    if (!['attribution', 'timeLabel'].every(field => typeof notice[field] === 'string' && notice[field].trim()) ||
        !Array.isArray(notice.paragraphs) || !notice.paragraphs.length ||
        notice.paragraphs.some(text => typeof text !== 'string' || !text.trim())) throw new Error(`Invalid organizer notice: ${record.id}`);
  }
  if (!Array.isArray(record.evidence) || !record.evidence.length) throw new Error(`Missing evidence: ${record.id}`);
  for (const item of record.evidence) {
    for (const field of ['id', 'label', 'description', 'caption']) {
      if (typeof item[field] !== 'string' || !item[field].trim()) throw new Error(`Missing evidence ${field}: ${record.id}`);
    }
    if (item.type === 'report') continue;
    const mediaPattern = item.type === 'video' ? /^assets\/[\w/.-]+\.mp4$/ : item.type === 'image' ? /^assets\/[\w/.-]+\.(png|jpe?g|webp)$/ : null;
    if (!mediaPattern || !mediaPattern.test(item.src) || item.src.split('/').includes('..')) throw new Error(`Invalid evidence path: ${record.id}`);
    await access(path.join(root, item.src));
    if (item.type === 'image') {
      if (typeof item.alt !== 'string' || !item.alt.trim() || !Number.isSafeInteger(item.width) || item.width <= 0 || !Number.isSafeInteger(item.height) || item.height <= 0) throw new Error(`Invalid image details: ${record.id}`);
      continue;
    }
    if (!/^assets\/[\w/.-]+\.(jpg|png|webp)$/.test(item.poster) || item.poster.split('/').includes('..')) throw new Error(`Invalid poster: ${record.id}`);
    await access(path.join(root, item.poster));
  }
}

const published = cases.filter(record => record.published).sort((a, b) => Date.parse(b.dateOpened) - Date.parse(a.dateOpened));
for (const record of published) {
  const team = teamById.get(record.suspectTeamId);
  const evidence = record.evidence.map((item, index) => item.type === 'report' ? `<figure class="case-evidence">
    <div class="frame-label top-label"><strong>${escape(item.label)}</strong><span>Witness report</span></div>
    <p>${escape(item.description)}</p>
    <figcaption class="case-caption">${escape(item.caption)}</figcaption>
  </figure>` : `<figure class="case-evidence">
    <div class="frame-label top-label"><strong>${escape(item.label)}</strong><span>${item.type === 'image' ? 'Supplied game material' : 'PNN reconstruction'}</span></div>
    ${item.type === 'image' ? `<img src="../../${escape(item.src)}" width="${item.width}" height="${item.height}" alt="${escape(item.alt)}" aria-describedby="evidence-${index}-description" loading="lazy" decoding="async">` : `<video controls playsinline preload="none" poster="../../${escape(item.poster)}" width="640" height="360" aria-label="${escape(item.label)}" aria-describedby="evidence-${index}-description">
      <source src="../../${escape(item.src)}" type="video/mp4">
      Your browser does not support embedded video.
    </video>`}
    <figcaption><p id="evidence-${index}-description">${escape(item.description)}</p><p class="case-caption">${escape(item.caption)}</p><a href="../../${escape(item.src)}">Open ${item.type === 'image' ? 'image' : 'video'} directly</a></figcaption>
  </figure>`).join('\n');
  const body = `
      <a class="case-back" href="../index.html">← All case files</a>
      <article>
        <header class="case-heading">
          <p class="eyebrow">${escape(record.caseNumber)} <span class="case-badge">${escape(record.status)}</span></p>
          <h1>${escape(record.incidentTitle)}</h1>
          <p class="intro">${escape(record.summary)}</p>
          <dl class="case-meta"><div><dt>Subject team</dt><dd>${escape(team.name)}</dd></div><div><dt>Opened</dt><dd><time datetime="${escape(record.dateOpened)}">${escape(dateLabel(record))}</time></dd></div><div><dt>PNN threat rating</dt><dd>${escape(record.threatLevel)}</dd></div></dl>
        </header>
        <div class="case-layout">
          <div class="case-report">
            <section><h2>The incident</h2><p>${escape(record.incidentDescription)}</p></section>
${(record.relatedCaseIds || []).filter(id => caseById.get(id).published).map(id => `<p class="case-caption">Previously on the PNN desk: <a href="../${escape(id)}/index.html">${escape(caseById.get(id).caseNumber)} — ${escape(caseById.get(id).incidentTitle)}</a></p>`).join('\n')}
${record.organizerNotice ? `<section class="organizer-notice"><h2>The witches' reminder</h2><p class="case-caption">${escape(record.organizerNotice.attribution)} · ${escape(record.organizerNotice.timeLabel)}</p><blockquote>${record.organizerNotice.paragraphs.map(text => `<p>${escape(text)}</p>`).join('')}</blockquote></section>` : ''}
            <section><h2>Suspected motive</h2><p>${escape(record.suspectedMotive)}</p></section>
            <section><h2>Investigator's note</h2><p>${escape(record.investigatorNote)}</p></section>
            <section class="case-assessment"><h2>Official PNN assessment</h2><p>${escape(record.disposition)}</p></section>
          </div>
          <aside aria-label="Subject team and evidence">
            <section class="case-team" aria-labelledby="subject-team-heading">
              <img src="../../${escape(team.logo)}" alt="${escape(team.name)} team logo" width="144" height="144">
              <div><p class="operation-label">Subject team · ${escape(team.color)}</p><h2 id="subject-team-heading">${escape(team.name)}</h2><p>Named in this PNN investigation.</p></div>
            </section>
            ${evidence}
          </aside>
        </div>
      </article>`;
  const directory = path.join(root, 'cases', record.id);
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, 'index.html'), page(`${record.caseNumber}: ${record.incidentTitle}`, record.summary, '../../', body));
}
const cards = published.map(record => `<article class="case-card"><p class="operation-label">${escape(record.caseNumber)} · ${escape(record.status)}</p><h2><a href="${record.id}/index.html">${escape(record.incidentTitle)}</a></h2><p>${escape(record.summary)}</p><p class="case-caption"><time datetime="${escape(record.dateOpened)}">${escape(dateLabel(record))}</time></p></article>`).join('\n');
await mkdir(path.join(root, 'cases'), { recursive: true });
await writeFile(path.join(root, 'cases/index.html'), page('Case files', 'PNN investigations from the Broomstick Challenge.', '../', `<p class="eyebrow">The Purrveillance desk</p><h1>Case files</h1><p class="intro">Clueso follows the facts. Preferably toward the pink team.</p><div class="case-list">${cards || '<p>No open files. Suspiciously quiet.</p>'}</div>`));
const latest = published[0];
const featuredMedia = latest?.evidence.find(item => item.type === 'image' || item.type === 'video');
const featured = latest ? `<article class="featured-case" aria-labelledby="featured-case-heading">
  <div class="frame-label top-label"><strong>Latest case file</strong><span>${escape(latest.caseNumber)}</span></div>
${featuredMedia ? `<a href="cases/${latest.id}/index.html" tabindex="-1" aria-hidden="true"><img class="featured-case-image" src="${escape(featuredMedia.type === 'image' ? featuredMedia.src : featuredMedia.poster)}" width="${featuredMedia.type === 'image' ? featuredMedia.width : 640}" height="${featuredMedia.type === 'image' ? featuredMedia.height : 360}" alt="" fetchpriority="high"></a>` : ''}
  <p class="operation-label">${escape(latest.status)} · ${escape(teamById.get(latest.suspectTeamId).name)}</p>
  <h2 id="featured-case-heading"><a href="cases/${latest.id}/index.html">${escape(latest.incidentTitle)}</a></h2>
  <p>${escape(latest.summary)}</p>
  <p class="case-caption"><time datetime="${escape(latest.dateOpened)}">${escape(dateLabel(latest))}</time></p>
  <a class="featured-case-link" href="cases/${latest.id}/index.html">${featuredMedia ? `Read the case &amp; ${featuredMedia.type === 'image' ? 'view' : 'watch'} the evidence` : 'Read the case &amp; witness report'} →</a>
</article>` : '<p class="intro">No open files. Suspiciously quiet.</p>';
const homePath = path.join(root, 'index.html');
const home = await readFile(homePath, 'utf8');
const featuredRegion = /<!-- BEGIN GENERATED FEATURED CASE -->[\s\S]*?<!-- END GENERATED FEATURED CASE -->/;
if (!featuredRegion.test(home)) throw new Error('Homepage featured-case markers are missing.');
await writeFile(homePath, home.replace(featuredRegion, `<!-- BEGIN GENERATED FEATURED CASE -->\n${featured}\n        <!-- END GENERATED FEATURED CASE -->`));
console.log(`Generated ${published.length} case page(s), the case index, and the homepage feature.`);
